import React, { useState } from 'react'
import { useParams, Link, Navigate } from 'react-router-dom'
import { Check, X, ArrowLeft, Zap, Shield, Bell, Download, Brain, Webhook } from 'lucide-react'
import { PLAN_DETAILS, PLANS_ORDERED } from '../config/planDetails'
import { createCheckoutSession } from '../lib/api'
import { usePlan } from '../hooks/usePlan'

const PRICE_IDS_MONTHLY = {
  member:   import.meta.env.VITE_STRIPE_PRICE_MEMBER,
  pro:      import.meta.env.VITE_STRIPE_PRICE_PRO,
  pro_plus: import.meta.env.VITE_STRIPE_PRICE_PRO_PLUS,
}
const PRICE_IDS_YEARLY = {
  member:   import.meta.env.VITE_STRIPE_PRICE_MEMBER_YEAR,
  pro:      import.meta.env.VITE_STRIPE_PRICE_PRO_YEAR,
  pro_plus: import.meta.env.VITE_STRIPE_PRICE_PRO_PLUS_YEAR,
}

const FEATURE_ICONS = {
  'Bell': Bell,
  'Shield': Shield,
  'Download': Download,
  'Brain': Brain,
  'Webhook': Webhook,
}

const WHAT_YOU_GET = {
  member: [
    { icon: Bell, title: 'Instant Push Alerts', desc: 'Get notified the moment a gauge you\'re watching crosses your alert threshold. Alerts arrive directly to your browser or device — no app download needed.' },
    { icon: Shield, title: '5 Gauge Subscriptions', desc: 'Set up monitoring for up to 5 gauges across the UGRA basin. Mix and match upstream headwaters and downstream gauges to cover your property or route.' },
    { icon: Zap, title: 'Real-Time Dashboard', desc: 'Full access to the live river corridor visualization, 48-hour sparklines, flood stage progress bars, and 1-hour rate-of-change indicators.' },
  ],
  pro: [
    { icon: Bell, title: 'SMS & Email Alerts', desc: 'Receive critical flood warnings by text message and email — so you stay informed even when you\'re away from your browser. Up to 15 gauge subscriptions.' },
    { icon: Brain, title: 'AI River Briefings', desc: 'Get a plain-English summary of current basin conditions generated by AI — updated on demand. Includes surge detection, forecast analysis, and flood outlook. 20 briefings per day.' },
    { icon: Zap, title: 'Enhanced Tracking', desc: 'All Member features plus higher subscription limits, multi-channel alerts, and priority access to new monitoring features.' },
  ],
  pro_plus: [
    { icon: Download, title: 'Data Exports', desc: 'Download raw historical stage and flow data as CSV or JSON for any UGRA gauge over any period. Perfect for engineers, researchers, and emergency planners.' },
    { icon: Webhook, title: 'Webhook Integrations', desc: 'Push alerts to any external system — Slack, PagerDuty, your own dashboard — via configurable webhook endpoints with HMAC signature verification.' },
    { icon: Zap, title: 'Early Access', desc: 'Be the first to test new features before they launch. Pro+ subscribers shape the roadmap and get early access to experimental tools and analytics.' },
  ],
}

async function handleUpgrade(planKey, yearly) {
  const ids = yearly ? PRICE_IDS_YEARLY : PRICE_IDS_MONTHLY
  const priceId = ids[planKey]
  if (!priceId) return
  try {
    const { url } = await createCheckoutSession(priceId)
    window.location.href = url
  } catch { /* Stripe not configured */ }
}

export default function PlanDetail() {
  const { tier } = useParams()
  const [yearly, setYearly] = useState(false)
  const { plan: currentPlan } = usePlan()

  const p = PLAN_DETAILS[tier]
  if (!p || tier === 'free') return <Navigate to="/pricing" replace />

  const price = yearly ? p.yearlyMonthlyPrice : p.monthlyPrice
  const isCurrent = currentPlan === tier
  const tierIndex = PLANS_ORDERED.indexOf(tier)
  const prevTier = tierIndex > 1 ? PLAN_DETAILS[PLANS_ORDERED[tierIndex - 1]] : null

  return (
    <div className="plan-detail-page">
      <Link to="/pricing" className="back-link" style={{ display: 'inline-flex', alignItems: 'center', gap: 6, marginBottom: 32 }}>
        <ArrowLeft size={14} /> Back to all plans
      </Link>

      {/* Hero */}
      <div className="plan-detail-hero" style={{ borderColor: p.color }}>
        {p.badge && (
          <div className="plan-detail-badge" style={{ background: p.color }}>
            {p.badge}
          </div>
        )}
        <h1 className="plan-detail-title" style={{ color: p.color }}>{p.name}</h1>
        <p className="plan-detail-tagline">{p.tagline}</p>

        <div className="pricing-toggle" style={{ marginTop: 24 }}>
          <button className={`pricing-toggle__btn${!yearly ? ' active' : ''}`} onClick={() => setYearly(false)}>Monthly</button>
          <button className={`pricing-toggle__btn${yearly ? ' active' : ''}`} onClick={() => setYearly(true)}>
            Yearly <span className="pricing-toggle__save">Save 20%</span>
          </button>
        </div>

        <div className="plan-detail-price">
          <span className="plan-detail-amount">${price.toFixed(2)}</span>
          <span className="plan-detail-period">/mo{yearly ? <>, billed <strong>${(price * 12).toFixed(2)}/yr</strong></> : null}</span>
        </div>

        {isCurrent ? (
          <button className="pricing-card__cta pricing-card__cta--current" disabled style={{ marginTop: 16, padding: '12px 40px', fontSize: '1rem' }}>
            Your current plan
          </button>
        ) : (
          <button
            className="pricing-card__cta"
            style={{ background: p.color, marginTop: 16, padding: '12px 40px', fontSize: '1rem' }}
            onClick={() => handleUpgrade(tier, yearly)}
          >
            <Zap size={16} /> {p.cta}
          </button>
        )}
      </div>

      {/* What you get */}
      <section className="plan-detail-section">
        <h2 className="plan-detail-section-title">What you get</h2>
        <div className="plan-detail-benefits">
          {(WHAT_YOU_GET[tier] || []).map((item, i) => {
            const Icon = item.icon
            return (
              <div key={i} className="plan-detail-benefit" style={{ '--plan-color': p.color }}>
                <div className="plan-detail-benefit-icon" style={{ background: `${p.color}22`, color: p.color }}>
                  <Icon size={22} />
                </div>
                <div>
                  <div className="plan-detail-benefit-title">{item.title}</div>
                  <div className="plan-detail-benefit-desc">{item.desc}</div>
                </div>
              </div>
            )
          })}
        </div>
      </section>

      {/* Full feature list */}
      <section className="plan-detail-section">
        <h2 className="plan-detail-section-title">Full feature list</h2>
        <ul className="plan-detail-features">
          {p.features.map((f, i) => (
            <li key={i} className={`plan-detail-feature${f.included ? '' : ' plan-detail-feature--no'}`}>
              {f.included
                ? <Check size={16} style={{ color: p.color, flexShrink: 0 }} />
                : <X size={16} style={{ color: '#475569', flexShrink: 0 }} />
              }
              <div>
                <strong>{f.label}</strong>
                <span style={{ color: '#94a3b8', marginLeft: 8 }}>{f.desc}</span>
              </div>
            </li>
          ))}
        </ul>
      </section>

      {/* Comparison vs lower tier */}
      {prevTier && (
        <section className="plan-detail-section">
          <h2 className="plan-detail-section-title">{p.name} vs {prevTier.name}</h2>
          <div className="plan-detail-comparison">
            <div className="plan-detail-comparison-col">
              <div className="plan-detail-comparison-header" style={{ color: prevTier.color }}>{prevTier.name}</div>
              <ul>
                {prevTier.features.filter(f => f.included).map((f, i) => (
                  <li key={i} className="plan-detail-comparison-item">{f.label}</li>
                ))}
              </ul>
            </div>
            <div className="plan-detail-comparison-col plan-detail-comparison-col--featured">
              <div className="plan-detail-comparison-header" style={{ color: p.color }}>{p.name} adds</div>
              <ul>
                {p.features.filter(f => f.included && !prevTier.features.find(pf => pf.included && pf.label === f.label)).map((f, i) => (
                  <li key={i} className="plan-detail-comparison-item plan-detail-comparison-item--new">
                    + {f.label}
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </section>
      )}

      {/* Use case */}
      <div className="plan-detail-usecase" style={{ borderColor: p.color }}>
        <p>"{p.useCases}"</p>
      </div>

      <div style={{ textAlign: 'center', marginTop: 40 }}>
        {isCurrent ? (
          <Link to="/account" className="pricing-card__cta pricing-card__cta--ghost" style={{ display: 'inline-flex' }}>
            Manage your subscription →
          </Link>
        ) : (
          <button
            className="pricing-card__cta"
            style={{ background: p.color, display: 'inline-flex', padding: '14px 56px', fontSize: '1.05rem' }}
            onClick={() => handleUpgrade(tier, yearly)}
          >
            <Zap size={16} /> {p.cta}
          </button>
        )}
      </div>
    </div>
  )
}
