export const GAUGES = [
  {
    id: '08165300',
    name: 'North Fork Guadalupe River near Hunt',
    shortName: 'North Fork near Hunt',
    basin: 'Upper Guadalupe',
    county: 'Kerr',
    type: 'river',
    lat: 30.0696,
    lng: -99.3378,
    order: 1,
    noaaSlug: null,
    floodStageFt: null,
    downstreamId: '08165500',
    downstreamMiles: 1.4,
    riseModel: { rainfallFactor: 1.1, decayHalfLifeHours: 6, lagHours: 0 }
  },
  {
    id: '08165500',
    name: 'Guadalupe River at Hunt',
    shortName: 'Hunt',
    basin: 'Upper Guadalupe',
    county: 'Kerr',
    type: 'river',
    lat: 30.0691,
    lng: -99.3153,
    order: 2,
    noaaSlug: 'HNTT2',
    floodStageFt: 10,
    downstreamId: '08166140',
    downstreamMiles: 8.6,
    riseModel: { rainfallFactor: 1.0, decayHalfLifeHours: 7, lagHours: 1 }
  },
  {
    id: '08166000',
    name: 'Johnson Creek near Ingram',
    shortName: 'Johnson Creek',
    basin: 'Johnson Creek / Guadalupe',
    county: 'Kerr',
    type: 'tributary',
    lat: 30.0749,
    lng: -99.2392,
    order: 2.5,
    noaaSlug: null,
    floodStageFt: null,
    downstreamId: '08166140',
    downstreamMiles: 4.4,
    riseModel: { rainfallFactor: 1.2, decayHalfLifeHours: 5, lagHours: 0 }
  },
  {
    id: '08166140',
    name: 'Guadalupe River above Bear Creek at Kerrville',
    shortName: 'Above Kerrville',
    basin: 'Upper Guadalupe',
    county: 'Kerr',
    type: 'river',
    lat: 30.0474,
    lng: -99.1817,
    order: 3,
    noaaSlug: null,
    floodStageFt: null,
    downstreamId: '08166200',
    downstreamMiles: 2.4,
    riseModel: { rainfallFactor: 0.9, decayHalfLifeHours: 9, lagHours: 1 }
  },
  {
    id: '08166200',
    name: 'Guadalupe River at Kerrville',
    shortName: 'Kerrville',
    basin: 'Upper Guadalupe',
    county: 'Kerr',
    type: 'river',
    lat: 30.0463,
    lng: -99.1403,
    order: 4,
    noaaSlug: 'KRVT2',
    floodStageFt: 9,
    downstreamId: '08166250',
    downstreamMiles: 9.2,
    riseModel: { rainfallFactor: 0.85, decayHalfLifeHours: 10, lagHours: 2 }
  },
  {
    id: '08166250',
    name: 'Guadalupe River near Center Point',
    shortName: 'Center Point',
    basin: 'Upper Guadalupe',
    county: 'Kerr',
    type: 'river',
    lat: 29.9444,
    lng: -99.0386,
    order: 5,
    noaaSlug: 'CNPT2',
    floodStageFt: null,
    downstreamId: '08167000',
    downstreamMiles: 9.8,
    riseModel: { rainfallFactor: 0.7, decayHalfLifeHours: 12, lagHours: 3 }
  },
  {
    id: '08167000',
    name: 'Guadalupe River at Comfort',
    shortName: 'Comfort',
    basin: 'Upper Guadalupe',
    county: 'Kendall',
    type: 'river',
    lat: 29.9666,
    lng: -98.907,
    order: 6,
    noaaSlug: 'CMFT2',
    floodStageFt: 26,
    downstreamId: '08167500',
    downstreamMiles: 27,
    riseModel: { rainfallFactor: 0.55, decayHalfLifeHours: 16, lagHours: 4 }
  },
  {
    id: '08167500',
    name: 'Guadalupe River near Spring Branch',
    shortName: 'Spring Branch',
    basin: 'Guadalupe',
    county: 'Comal',
    type: 'river',
    lat: 29.873,
    lng: -98.409,
    order: 7,
    noaaSlug: null,
    floodStageFt: null,
    downstreamId: '08167800',
    downstreamMiles: 11,
    riseModel: { rainfallFactor: 0.45, decayHalfLifeHours: 20, lagHours: 6 }
  },
  {
    id: '08167800',
    name: 'Canyon Lake near New Braunfels',
    shortName: 'Canyon Lake',
    basin: 'Guadalupe',
    county: 'Comal',
    type: 'reservoir',
    lat: 29.868,
    lng: -98.197,
    order: 8,
    noaaSlug: null,
    floodStageFt: null,
    downstreamId: '08168500',
    downstreamMiles: 3,
    riseModel: { rainfallFactor: 0.05, decayHalfLifeHours: 240, lagHours: 12, passThrough: true }
  },
  {
    id: '08168500',
    name: 'Guadalupe River above Comal River at New Braunfels',
    shortName: 'New Braunfels',
    basin: 'Guadalupe',
    county: 'Comal',
    type: 'river',
    lat: 29.705,
    lng: -98.116,
    order: 9,
    noaaSlug: null,
    floodStageFt: null,
    downstreamId: null,
    downstreamMiles: null,
    riseModel: { rainfallFactor: 0.4, decayHalfLifeHours: 24, lagHours: 8 }
  },
  {
    id: '08178800',
    name: 'Medina River at Bandera',
    shortName: 'Medina at Bandera',
    basin: 'Medina / Hill Country',
    county: 'Bandera',
    type: 'river',
    lat: 29.725,
    lng: -99.074,
    order: 20,
    noaaSlug: null,
    floodStageFt: null,
    downstreamId: null,
    downstreamMiles: null,
    riseModel: { rainfallFactor: 0.95, decayHalfLifeHours: 8, lagHours: 1 }
  },
  {
    id: '08195000',
    name: 'Frio River at Concan',
    shortName: 'Frio at Concan',
    basin: 'Frio / Hill Country',
    county: 'Uvalde',
    type: 'river',
    lat: 29.488,
    lng: -99.704,
    order: 30,
    noaaSlug: null,
    floodStageFt: null,
    downstreamId: null,
    downstreamMiles: null,
    riseModel: { rainfallFactor: 1.1, decayHalfLifeHours: 6, lagHours: 0 }
  },
  {
    id: '08198000',
    name: 'Sabinal River near Sabinal',
    shortName: 'Sabinal River',
    basin: 'Sabinal / Hill Country',
    county: 'Uvalde',
    type: 'river',
    lat: 29.329,
    lng: -99.467,
    order: 31,
    noaaSlug: null,
    floodStageFt: null,
    downstreamId: null,
    downstreamMiles: null,
    riseModel: { rainfallFactor: 1.15, decayHalfLifeHours: 5, lagHours: 0 }
  },
  {
    id: '08189500',
    name: 'Nueces River at Laguna',
    shortName: 'Nueces at Laguna',
    basin: 'Nueces / Hill Country',
    county: 'Uvalde',
    type: 'river',
    lat: 29.425,
    lng: -99.996,
    order: 32,
    noaaSlug: null,
    floodStageFt: null,
    downstreamId: null,
    downstreamMiles: null,
    riseModel: { rainfallFactor: 1.0, decayHalfLifeHours: 7, lagHours: 1 }
  }
]

export const REFRESH_MS = 300_000
export const STALE_AFTER_MINUTES = 20
export const FAST_FLOW_MPH = 4
export const FLOOD_FLOW_MPH = 8
