export const PLAN_DETAILS = {
  free: {
    key: 'free',
    name: 'Free',
    tagline: 'Quick overview of UGRA river data',
    monthlyPrice: 0,
    yearlyMonthlyPrice: 0,
    color: '#64748b',
    priceEnvMonthly: null,
    priceEnvYearly: null,
    features: [
      { included: true,  label: 'Real-time dashboard', desc: 'Full river corridor and live gauge cards' },
      { included: true,  label: 'Live gauge data', desc: 'Current stage, flow, and 48-hour sparklines' },
      { included: false, label: 'Alert subscriptions', desc: 'Requires Member plan or higher' },
      { included: false, label: 'Mobile push alerts', desc: 'Requires Member plan or higher' },
      { included: false, label: 'SMS & email alerts', desc: 'Requires Pro plan or higher' },
      { included: false, label: 'AI river briefings', desc: 'Requires Pro plan or higher' },
      { included: false, label: 'Data exports', desc: 'Requires Pro+ plan' },
      { included: false, label: 'Early access features', desc: 'Requires Pro+ plan' },
    ],
    useCases: 'Ideal for casual users who just want a quick overview of Guadalupe River conditions without needing alerts.',
    cta: 'Get started free',
  },
  member: {
    key: 'member',
    name: 'Kerr County Member',
    tagline: 'Essential flood awareness for Kerr County residents',
    monthlyPrice: 4.99,
    yearlyMonthlyPrice: 3.99,
    color: '#10b981',
    priceEnvMonthly: 'VITE_STRIPE_PRICE_MEMBER',
    priceEnvYearly: 'VITE_STRIPE_PRICE_MEMBER_YEAR',
    features: [
      { included: true,  label: 'Everything in Free', desc: 'Full dashboard and live data access' },
      { included: true,  label: '5 alert subscriptions', desc: 'Monitor up to 5 gauges simultaneously' },
      { included: true,  label: 'Mobile push alerts', desc: 'Instant browser/device push notifications' },
      { included: false, label: 'SMS & email alerts', desc: 'Requires Pro plan or higher' },
      { included: false, label: 'AI river briefings', desc: 'Requires Pro plan or higher' },
      { included: false, label: 'Data exports', desc: 'Requires Pro+ plan' },
      { included: false, label: 'Early access features', desc: 'Requires Pro+ plan' },
    ],
    useCases: 'Perfect for Kerr County homeowners who need to know when the Guadalupe is rising before it reaches their property.',
    cta: 'Upgrade to Member',
    badge: null,
  },
  pro: {
    key: 'pro',
    name: 'Pro',
    tagline: 'Enhanced tracking with AI forecasting',
    monthlyPrice: 9.99,
    yearlyMonthlyPrice: 7.99,
    color: '#3b82f6',
    priceEnvMonthly: 'VITE_STRIPE_PRICE_PRO',
    priceEnvYearly: 'VITE_STRIPE_PRICE_PRO_YEAR',
    features: [
      { included: true,  label: 'Everything in Member', desc: 'All Member plan features included' },
      { included: true,  label: '15 alert subscriptions', desc: 'Track up to 15 gauges across the basin' },
      { included: true,  label: 'SMS & email alerts', desc: 'Text and email notifications in addition to push' },
      { included: true,  label: 'AI river briefings', desc: 'AI-powered forecasting with 20 calls/day' },
      { included: false, label: 'Data exports', desc: 'Requires Pro+ plan' },
      { included: false, label: 'Early access features', desc: 'Requires Pro+ plan' },
    ],
    useCases: 'Built for emergency managers, ranchers, and anyone who needs multi-channel alerts and AI-powered insight into Guadalupe River trends.',
    cta: 'Upgrade to Pro',
    badge: 'Most Popular',
  },
  pro_plus: {
    key: 'pro_plus',
    name: 'Pro+',
    tagline: 'Unlimited access with advanced tools',
    monthlyPrice: 19.99,
    yearlyMonthlyPrice: 15.99,
    color: '#a855f7',
    priceEnvMonthly: 'VITE_STRIPE_PRICE_PRO_PLUS',
    priceEnvYearly: 'VITE_STRIPE_PRICE_PRO_PLUS_YEAR',
    features: [
      { included: true,  label: 'Everything in Pro', desc: 'All Pro plan features included' },
      { included: true,  label: 'Unlimited subscriptions', desc: 'Monitor every gauge in the UGRA basin' },
      { included: true,  label: 'All alert channels', desc: 'Push, SMS, email, and webhook support' },
      { included: true,  label: 'Unlimited AI briefings', desc: 'No daily cap on AI river intelligence calls' },
      { included: true,  label: 'Data exports', desc: 'Download historical readings as CSV/JSON' },
      { included: true,  label: 'Early access features', desc: 'Be first to try new tools and analytics' },
    ],
    useCases: 'For power users, water authorities, and researchers who need complete access, data portability, and first access to the latest UGRA Sentinel features.',
    cta: 'Upgrade to Pro+',
    badge: null,
  },
}

export const PLANS_ORDERED = ['free', 'member', 'pro', 'pro_plus']
